XsdTransformer.Web.Site/Models/CsvTransformModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web;
using FluentValidation.Attributes;
using XsdTransformer.Web.Site.Validators;

namespace XsdTransformer.Web.Site.Models
{
    [Validator(typeof(CsvTransformValidator))]
    public class CsvTransformModel
    {
        [DisplayName("Files")]
        public IEnumerable<HttpPostedFileBase> Files { get; set; }

        [DisplayName("XSD file name")]
        public string XsdFileName { get; set; }

        [DisplayName("XML file name")]
        public string XmlFileName { get; set; }
    }

    public class CsvTransformViewModel
    {
        [DisplayName("CSV")]
        public string Csv { get; set; }

        [DisplayName("Validation result")]
        public string ValidationResult { get; set; }
    }
}

XsdTransformer.Web.Site/Controllers/CsvController.cs
using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Xml.Schema;
using XsdTransformer.Core;
using XsdTransformer.Web.Site.Models;

namespace XsdTransformer.Web.Site.Controllers
{
    public class CsvController : Controller
    {
        private readonly IXsdLoader _loader;

        private readonly IXsdTransformer _transformer;

        public CsvController(IXsdLoader loader, IXsdTransformer transformer)
        {
            _loader = loader;
            _transformer = transformer;
        }

        public ActionResult Index()
        {
            return View(new CsvTransformModel());
        }

        [HttpPost]
        public ActionResult Index(CsvTransformModel model)
        {
            if (ModelState.IsValid)
            {
                var folder = Guid.NewGuid().ToString("N");
                var path = EnsureEmptyFolder(folder);
                SaveFiles(model, path);

                return RedirectToAction("Transform", new { folder, model.XsdFileName, model.XmlFileName });
            }

            return View(model);
        }

        public ActionResult Transform(string folder, string xsdFileName, string xmlFileName)
        {
            var result = new CsvTransformViewModel();

            try
            {
                var xsdPath = GetFolderPath(folder + "\\" + xsdFileName);
                var xmlPath = GetFolderPath(folder + "\\" + xmlFileName);
                var document = _loader.Load(xsdPath, xmlPath);
                var validationResult = _loader.GetValidationResult();

                Cleanup(folder);
                result.ValidationResult = validationResult.Aggregate("", (c, n) => string.Format("{0}\n{1}", c, n));

                if (_loader.GetValidationResult().All(x => x.Key != XmlSeverityType.Error))
                    result.Csv = _transformer.TransformXml(document);
            }
            catch (Exception ex)
            {
                result.ValidationResult = ex.ToString();
            }

            return View(result);
        }

        private void RecursiveDelete(DirectoryInfo baseDir)
        {
            if (!baseDir.Exists)
                return;

            foreach (var dir in baseDir.EnumerateDirectories())
            {
                RecursiveDelete(dir);
            }

            baseDir.Delete(true);
        }

        private void Cleanup(string folder)
        {
            var path = GetFolderPath(folder);

            RecursiveDelete(new DirectoryInfo(path));
        }

        private void SaveFiles(CsvTransformModel model, string path)
        {
            foreach (var file in model.Files)
            {
                using (var sr = new StreamReader(file.InputStream))
                {
                    var content = sr.ReadToEnd();

                    // Set any import file references within the XSD to newly created path.
                    content = Regex.Replace(content, "schemaLocation=\"(.+)?\"", string.Format("schemaLocation=\"file:///{0}/$1\"", path.Replace("\\", "/")));

                    using (var sw = System.IO.File.CreateText(Path.Combine(path, file.FileName)))
                        sw.Write(content);
                }
            }
        }

        private string GetFolderPath(string name)
        {
            return Path.Combine(Server.MapPath("~/App_Data/"), name);
        }

        private string EnsureEmptyFolder(string name)
        {
            var path = GetFolderPath(name);

            if (Directory.Exists(path))
                Directory.Delete(path, true);

            Directory.CreateDirectory(path);
            return path;
        }
    }
}

XsdTransformer.Web.Site/Views/Csv/Index.cshtml
@model XsdTransformer.Web.Site.Models.CsvTransformModel
@using (Html.BeginForm("Index", "Csv", FormMethod.Post, new { id = "UploadForm", enctype = "multipart/form-data", @class = "form" }))
{
    <div class="form-row col-2">
        @Html.LabelFor(m => m.Files, new { @class = "form-col" })
        <div class="form-col">
            <input type="file" multiple="multiple" name="@Html.NameFor(m => m.Files)" id="@Html.IdFor(m => m.Files)" data-val-required="Please select files to upload." data-val="true" />
            @Html.ValidationMessageFor(m => m.Files)
        </div>
    </div>
    <div class="form-row col-2">
        @Html.LabelFor(m => m.XsdFileName, new { @class = "form-col" })
        <div class="form-col">
            @Html.TextBoxFor(m => m.XsdFileName)
            @Html.ValidationMessageFor(m => m.XsdFileName)
        </div>
    </div>
    <div class="form-row col-2">
        @Html.LabelFor(m => m.XmlFileName, new { @class = "form-col" })
        <div class="form-col">
            @Html.TextBoxFor(m => m.XmlFileName)
            @Html.ValidationMessageFor(m => m.XmlFileName)
        </div>
    </div>
    <div class="form-row">
        <button type="submit">
            Transform</button>
    </div>
}

XsdTransformer.Web.Site/Views/Csv/Transform.cshtml
@model XsdTransformer.Web.Site.Models.CsvTransformViewModel
<div id="transform" class="form">
    <div class="form-row col-1">
        @Html.LabelFor(x => x.Csv, new { @class = "form-col" })
        <div class="form-col">
            @Html.TextAreaFor(x => x.Csv, new { wrap = "off" })
        </div>
    </div>
    @if (!string.IsNullOrWhiteSpace(Model.ValidationResult))
    {
        <div class="form-row col-1">
            @Html.LabelFor(x => x.ValidationResult, new { @class = "form-col" })
            <div class="form-col">
                @Html.TextAreaFor(x => x.ValidationResult, new { rows = 10, wrap = "off" })
            </div>
        </div>
    }
</div>

XsdTransformer.Web.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="wrapper">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>